{{- if .Values.rcon.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}-rcon
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.rcon.type }}
  ports:
  - name: rcon
    port: {{ .Values.rcon.port }}
    nodePort: {{ .Values.rcon.port}}
    protocol: TCP
  selector:
    app: {{ template "factorio-server-charts.fullname" . }}
{{- end }}