apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: factorio
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: UDP
    #nodePort: {{ .Values.service.port}}
  selector:
    app: {{ template "factorio-server-charts.fullname" . }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
